[book]
authors = ["wangchao"]
language = "en"
multilingual = false
src = "src"
title = "Linux自记录文档"

[build]
build-dir = "docs"

[output.html]
no-section-label = true

[output.html.fold]
enable = true
level = 1